### ISSUE TITLE
Provide email address along with address data

### ISSUE THREAD

**Issue by jvkersch** [jeffschenck/authorizesauce#28]
Authorize.net has a setting to send payment notifications to users. For this to work, the user's email address needs be sent along with the address data; is this currently supported by AuthorizeSauce?

**Comment by jeffschenck** [comment]
This is not currently supported, and I'd personally be wary about adding it. Part of the design philosophy behind the library is to minimize the use of Authorize.net as much as possible — whatever can be done by me on my own servers, I want to have control of. So AuthorizeSauce handles the sensitive stuff you can't really do on your own — charging cards and saving cards.
